import { buildPrompt, streamCerebras, extractHtml, type GenArgs } from '@/lib/cerebras'
import { templateFor } from '@/lib/templates'
import type { Kind } from '@/lib/types'

export const runtime = 'edge'

// POST /api/generate
// Streams the artifact HTML as it is generated by Cerebras GLM-4.7.
// On ANY failure (no key, network, model error) it falls back to a cached
// template so the wow (runs live in-app) never depends on a live model call.
export async function POST(req: Request) {
  let args: GenArgs
  try {
    args = (await req.json()) as GenArgs
  } catch {
    args = { kind: 'game' }
  }
  const kind: Kind = (args.kind ?? 'game') as Kind

  const encoder = new TextEncoder()
  const stream = new ReadableStream({
    async start(controller) {
      const send = (obj: unknown) =>
        controller.enqueue(encoder.encode(JSON.stringify(obj) + '\n'))

      try {
        const prompt = buildPrompt({ ...args, kind })
        let acc = ''
        let any = false
        for await (const chunk of streamCerebras(prompt)) {
          any = true
          acc += chunk
          // stream live progress to the client
          send({ type: 'progress', chars: acc.length })
        }
        const html = extractHtml(acc)
        if (!any || !/<html|<!doctype/i.test(html)) throw new Error('empty')
        send({ type: 'done', html, source: 'cerebras' })
      } catch {
        // Fallback: cached template for this kind. For refines, just keep the
        // current HTML so the demo never breaks.
        const fallback =
          args.current && args.refine
            ? args.current
            : templateFor(kind).html
        send({ type: 'done', html: fallback, source: 'fallback' })
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'content-type': 'application/x-ndjson; charset=utf-8',
      'cache-control': 'no-cache',
    },
  })
}
